### ISSUE TITLE
Apply low-hanging fruit fixes

### ISSUE THREAD

**Issue by hyperupcall** [hyperupcall/bats-common-utils#1]
This is a meta issue that tracks issues and PRs from repositories that were merged into this one that I likely plan to fix (at least initially). They include

Edit: Issues are now tracked in [./issues.md](https://github.com/hyperupcall/bats-all/blob/main/issues.md) to prevent spamming references

**Comment by jwheeler31** [comment]
Submitted [PR](https://github.com/bats-core/bats-assert/pull/37) for bats-core/bats-assert#31

**Comment by hyperupcall** [comment]
> Submitted [PR](https://github.com/bats-core/bats-assert/pull/37) for [bats-core/bats-assert#31](https://github.com/bats-core/bats-assert/issues/31)

Thank you, I'll merge that in here soon :) (edit: done!)

I'll also add that I'm pretty sure there is no difference in behavior with the quotes in this case, due to the order Bash carries out various expansions (but correct me if I am wrong). The Bash man page says

> Word splitting and pathname expansion are not performed on the words between the [[ and ]]; tilde expansion, parameter
              and variable expansion, arithmetic expansion, command substitution, process substitution, and quote re‐
              moval are performed.  Conditional operators such as -f must be unquoted to be recognized as primaries.

And in both cases the right-hand-side is quoted so glob matching never occurs

**Comment by jwheeler31** [comment]
Interesting. I can modify the existing PR to remove the quotes - I think it's become muscle-memory at this point.

**Comment by hyperupcall** [comment]
You can add a commit if you want, but at least for me it's not really necessary since I already merged your changes in my [fork](https://github.com/hyperupcall/bats-assert/commits/master), and this repository incorporates that revision :P
